# SPDX-FileCopyrightText: 2024 Foundation Devices, Inc. <hello@foundation.xyz>
# SPDX-License-Identifier: GPL-3.0-or-later

[toolchain]
channel = "nightly-2025-04-03"
components = ["rustfmt", "clippy", "rustc", "llvm-tools", "rust-src"]
targets = ["thumbv7em-none-eabi"]
profile = "minimal"
